r3labs/sse

client.go

The subscription events channel was only closed in the case where an error was encountered while reading from the stream, but not in the case such error was encountered while connecting to it.

Consistently close channel on error

---

server.go

I had a use-case which required that I had access to a list of streams being stored by the server.
Without exposing the steams property I'd have to independently store the steams myself (when I create them) which seemed a bit wasteful considering the slice already exists within the server struct.
I thought I'd pull request in-case anyone else wanted this, if this isn't something you'd like within the repository feel free to close my request.
I also don't mind creating a new method 'Servers()' which returns the slice in-case you want to keep the internal property private.

Exposes the streams property on server

---

stream.go
stream_test.go

Adds a boolean flag to the Stream struct to allow enabling/disabling of replaying the eventlog to newly added subscribers.
Ensures backward-compatibility of functionality by defaulting the AutoReplay flag to true, which would emulate past behaviour.
Also added tests for when AutoReplay is both enabled and disabled.
Let us know if there's anything to be improved as part of this PR.

Adds AutoReplay option to Stream

---

stream_test.go

Added a sleep before adding the subscriber to the stream to ensure the event is acknowledged before the subscriber is added.
The test should now pass consistently.

Fixes AutoReplay disabled test

---

http.go

My team and I ran into an issue with subscribing to the HTTPHandler from a web client. It seems like the existing format for the event doesn't match [the W3 recommendation](https://www.w3.org/TR/eventsource/).
W3 specifies that there should be a an empty new-line character between events.
For example:
```
id: 0
event: add
data: this is the first event
id: 1
event: add
data: this is the second event
id: 2
event: add
data: this is the third event
```
Currently the HTTPHandler doesn't new-line separate.
For example:
```
id: 0
event: add
data: this is the first event
id: 1
event: add
data: this is the second event
id: 2
event: add
data: this is the third event
```
The existing client in this library doesn't care about this distinction, but a web browser such as Chrome or Safari or a JS client …

Update HTTPHandler to send events with new-line seperation

---

client.go

This should prevent the issue where the connection isn't closed when unsubscribing.

Closing client connection when Unsubscribe() is called.

---

client.go

As there is no more expected input on the event stream when reading `EOF` the subscription can be safely closed.
When an unexpected error e.g. `unexpected EOF` occurs the request is retried as per usual behavior.

Close blocking event stream subscription on EOF

---

server.go
server_test.go

When creating a stream via `CreateStream()`, a new stream is always created even if a stream with the same `id` already exists, causing a memory leak where goroutines are created via `str.run()` but never closed.
Instead of closing the newly created stream if it exists, this PR fixes the bug by reorganizing the `CreateStream()` function so that it checks to see if the server has a stream with the given `id` before creating a new stream. 
These changes are reflected in the tests!
```
make test
```

fixing memory leak when creating a new stream

---

client.go

if publishing an empty string (which can happen in our use case since we are passing output from a cli command):
```
server.Publish("messages", &sse.Event{
Data: []byte(""),
})
```
and subscribing to the event:
```
client.Subscribe("messages", func(msg *sse.Event) {
// Got some data!
fmt.Println(msg.Data)
})
```
causes a panic (index is out of range) when calling `trimHeader`. the empty byte slice results in `data[-1]`
i've also removed the length check in processEvent to display empty lines. AFAIK empty strings are allowed according to the W3C.

enable empty event lines

---

client.go

Wrapped access to subscribed map in mutex.
See https://github.com/r3labs/sse/issues/48

Issue #48: panic: unsafe map write when calling client.SubscribeChan() multiple times (concurrently) with the same channel.

---

client.go

Default `backoff.ExponentialBackOff()` values did not fit my needs (firstly because of `MaxElapsedTime` limit upon the expiry of which client stops reconnection attempts), so i've made some changes to sse-client code. Tests are not ready yet, but i hope to complete them someday :)
Some examples:
```go
import (
...
backoff "gopkg.in/cenkalti/backoff.v1"
)
func main() {
customBackoff := &backoff.ExponentialBackOff{
InitialInterval:     500 * time.Millisecond,
RandomizationFactor: 0.5,
Multiplier:          1.2,
MaxInterval:         10 * time.Second,
MaxElapsedTime:      1000 * time.Hour,
Clock:               backoff.SystemClock,
}
customBackoff.Reset()
client := sse.NewClient("http://server/events")
client.ReconnectStrategy = customBackoff
}
```
or we can just use simpler …

Allow a client to specify custom reconnection strategy

---

client.go

Only assign up to the length of the decoded base64 message.

Don't send more data than we decoded

---

client.go
event.go

We cannot cancel the subscription with current api. This PR adds context aware apis and also keep current apis backward compatible.

Add context aware apis for better lifecycle management

---

client.go
client_test.go

The unsubscribe function is blocking. The problem lies with the unsubscribe channel only being checked when sending the next event, so an event has to be read from the stream first. This means the unsubscribe will not happen if there aren't any events arriving currently.
A test was added to demonstrate this issue (`TestClientUnsubscribeNonBlock`). Calls to `Unsubscribe` should return quickly (or at least not network dependent), but in the case of no further data they are essentially blocked.
The solution here is to move the event reading to a separate async reader loop. That way we have a chance to bail before we read an event (or while waiting to) and before we send it downstream.
There was some additional refactoring done including 
- Use of readLoop to reduce duplication between the …

Unsubscribe unblock

---

event_log.go
http.go
stream.go
subscriber.go

As string comparision isn't nature than number, and will send wrong message while set Last-Event-ID to number.
scenario:
1. message id is 100
2. send http request with Last-Event-ID=10
3. server will send messages as follow: 2,3,4,5,6,7,8,9,11,12...

use Last-Event-ID as int, not string

---

event.go

The SSE spec defines `CR` (`\r`), `LF` (`\n`) and `CRLF` (`\r\n`) as permitted end-of-line sequences.  However, it does not state that a producer must pick one and use only that format - it is possible to encounter `\r\n\n` or `\n\r\n`.  This project currently does not recognize those permutations.
This patch detects the earliest occurrence of any of the (sensible) permutations, and advances the stream by the length of that sequence.  By sensible permutations, I am assuming that `\r` won't be mixed in with any of the other possible sequences, as I believe it is rarely used now.
I tested it against two SSE sources: one that sends only `\n\n` and one that sends `\n\r\n`, and it behaves correctly for both.

Handle more permutations of newlines

---

client.go

Given the code
```golang
// in a goroutine:
for {
err := client.SubscribeRawWithContext(ctx, func(msg *sse.Event) {
logger.Printf("SSE Message ID=%q Retry=%q Event=%q len(Data)=%d\n", string(msg.ID), string(msg.Retry), string(msg.Event), len(msg.Data))
})
if err != nil {
logger.Println("SubscribeRawWithContext stopped:", err)
} else {
logger.Println("SubscribeRawWithContext done; retrying")
time.Sleep(1 * time.Second)
}
}
```
the SubscribeRawWithContext method would be called every 1 second if the HTTP request returns a StatusCode other than 200 without a stream result. This happens because the EventStreamReader.startReadLoop will convert `io.EOF` into a non-error. This gives the users of the SSE lib no context as to why the `SubscribeRawWithContext` is called every single second (and …

ResponseValidator & ReconnectNotify

---

client.go

When I use the latest version(v2.2.0), I got an issue in heavy network I/O.
I'm using `sse` as client, when I send an event stream request to server with header `Last-Event-ID: 0`, server sends lots of events to client, then I found some message's fields, such as `ID` & `Event`, was not the original value.
This might be caused by a byte slice was a reference, not a value.
So I use a copied value to these fields (`ID`, `Event`, `Retry`) to avoid this situation.

Use copied fields to avoid byte slice was reused.

---

client.go
client_test.go

include http error status on subscription error

---

server.go

Remove "Access-Control-Allow-Origin" from NewServer Headers.
It has many implications like this error:
```
Access to resource at 'http://localhost:3000/streams/v1?stream=test' from origin 'http://localhost:5000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

Remove "Access-Control-Allow-Origin" from NewServer Headers

---

http.go

According to https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format we can send a message as a comment if it starts with ":".
> Note: The comment line can be used to prevent connections from timing out; a server can send a comment periodically to keep the connection alive.

detect if data is a comment

---

http.go
http_test.go
server.go
stream.go
stream_test.go
subscriber.go

@purehyperbole, @codewinch I think this is needed to cleanup a bit especially if there are many streams for short periods, something like `/events?stream=<eventIDEachTimeDifferent>`.
But the new test sometimes is green sometimes not. What do you think?
It always turns green if I add this line:
```go
time.Sleep(1*time.Second)
```
after the line:
```go
sub.close()
```
in `http.go`.
But I don't like `time.Sleep()` in code.
Can we better "wait" for `sub.close()` to finish?

remove stream if AutoStream enabled when no more subscribers

---

client.go
client_test.go
event.go

Note: Defaults to the normal bufio values.

allow configuration of max buffer client size

---

http.go

This change makes the SSE server work with chi's Compress middleware. Compress uses response headers to determine if the response body is [compressible](https://github.com/go-chi/chi/blob/0316d5a1df8598eceb137f5f77945be56810b564/middleware/compress.go#L281), so the headers should be written out before flushing. Hope this change can save other users a couple of hours of digging.

Add w.WriteHeader() call before first Flush()

---

go.mod
go.sum

Closes #126 by updating testify from v1.4.0 to v1.7.0, which in turn updates gopkg.in/yaml.v3.

Update testify from v1.4.0 to v1.7.0

---

client.go

Fix bug where functions that call `SubscribeWithContext()` can end up in an endless loop waiting for input from `errorChan` or `eventChan` while context is done.

fix context handling SubscribeWithContext

---

event.go

The given `maxBufferSize` can be smaller than the default value size of 4096 that is passed to `scanner.Buffer()`. This can lead to unintended behaviour.
So this PR is proposing to use the minimum value of both.

fix inital buffer size

---

client_test.go
http.go
server.go
server_test.go
stream.go
stream_test.go
subscriber.go

this change makes callback function to support when client register or un-register SSE
issue : #132 
**example server**
```go	
package main
import (
"fmt"
"net/http"
"time"
"github.com/r3labs/sse/v2"
)
func main() {
c := make(map[string]int32)
onRegister := func(str *sse.Stream) {
c[str.ID]++
fmt.Printf("\U0001F7E2 [channel : %s] client is registered (%d registered)\n", str.ID, c[str.ID])
}
onUnRegister := func(str *sse.Stream) {
c[str.ID]--
fmt.Printf("🔴 [channel : %s] client is registered (%d registered)\n", str.ID, c[str.ID])
}
server := sse.NewWithCallback(onRegister, onUnRegister)
server.AutoStream = true
server.AutoReplay = false
// Create a new Mux and set the handler
mux := http.NewServeMux()
mux.HandleFunc("/events", server.ServeHTTP)
go func() {
for {
time.Sleep(2 * time.Second) …
```

feature(server) : add callback function for register and un-register

---

client.go
client_test.go
event.go
event_log.go
http.go

skip any comments sent to the client

---

client.go
client_test.go

select ctx.Done() in operation() will cause operation() return before c.readLoop(), 
the unbuffered channel name "erChan" will block c.readLoop() after io.EOF,
c.readLoop() will never return.
because of the error return from operation() is not nil,
the backoff.RetryNotify() will never return

Fix bug, goroutine leak in the functions SubscribeWithContext()

---

client.go
client_test.go

OnConnect is callback when request is successful. IMO thisshould part of the client api. if we follow SSE spec then events should be named OnClose and OnOpen.

Client OnConnect event added

---

client.go
http_test.go
server.go
stream.go
stream_test.go

Changes:
1. Optimized locking so publishing doesn't prevent closing, for example. I found this in another of my branch, which tried to use `ResponseController` newly introduced in Go 1.20 to detect disconnected clients (via the error returned by the new `Flush()` method). That ended up not working well due to TCP retransmission so I abandoned the work, but thinking the optimization should be useful.
2. Fixed two race conditions found with `go test -race`.
No tests since I'm not quite familiar with the codebase yet, but if anyone can point me in which way I can add them, I'd be happy to do.
I also noticed that this test frequently failed on my macOS even in `master`. I can have a look too if that's desirable.
```
=== RUN   TestSubscribeWithContextDone
client_test.go:423:
Error Trace: …
```

Optimize locking

---

server.go

It adds one commit on top of https://github.com/r3labs/sse/pull/143 to add a `PublishNoBlock` method. It's useful in my use case, but I'm not sure how others would think, so feel free to reject it!

Non blocking publish
